### ISSUE TITLE
Is config file required?

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sample-project#4]
I can understand when there are several preferences to be set but in our case where it is just the path to the data dir, would it be better to just offer users to set an environment variable just like sklearn does (see [here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/datasets/_base.py#L39-L41
))?

**Comment by larsoner** [comment]
> I can understand when there are several preferences to be set but in our case where it is just the path to the data dir, would it be better to just offer users to set an environment variable just like sklearn does (see here)?

In MNE we have lots of datasets, some are huge. So it would make sense that users might want data stored in different locations.

As for env var versus config, sure you stick to just using an env var but it's less convenient than having a little preferences/paths file on the system. FWIW in MNE we have a hierachy that's followed:

1. Use the `path` provided in the `data_path(path=None, ...)` function. If None...
2. Use the env var `MNE_DATASETS_WHATEVER_PATH`. If None...
3. Use the config file var `MNE_DATASETS_WHATEVER_PATH`. If None...
4. Use the generic env var `MNE_DATASETS_PATH`. If None...
5. Use the generic config file var `MNE_DATASETS_PATH`. IF None...
6. Use `~/mne_data/MNE-whatever-data` and prompt the user (unless `data_path(..., update_path=True)`) to ensure it's okay to download there set the path in the config file

**Comment by lucyleeow** [comment]
Sure that makes sense. I would like to make the template general and reasonably basic and users with more complex requirements can adapt to their needs. 

I could add an env var option, so packages with less complex data needs (e. g., sklearn) can opt to only use this (and not the  config). Though that may be making the template complex as I would need to amend `data_download` to allow users to not create a config file if an env var exists.

**Comment by lucyleeow** [comment]
Actually I don't think that works. I'll just leave it as is because I don't know what the best solution is.
